[package]
name = "vimlfmt"
version = "0.1.0"
authors = ["Zandr Martin <zandrmartin@gmail.com>"]
description = "A formatter for VimL code"
edition = "2018"

[dependencies]
viml-parser = { path = "parser" }
clap = "2.32.0"
