[package]
name = "viml-parser"
version = "0.1.0"
authors = ["Zandr Martin <zandrmartin@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.0.5"
lazy_static = "1.2.0"
maplit = "1.0.1"
bitflags = "1.0.4"
